### ISSUE TITLE
search-unifiedauditlog highcompletenes parameter

### ISSUE THREAD

**Issue by Passimist** [invictus-ir/Microsoft-Extractor-Suite#41]
Hello everyone,

first of thank you for providing this cool project. I stumbled upon a parameter in the documentation of the search-unifiedauditlog cmdlet that got me worried: https://learn.microsoft.com/en-us/powershell/module/exchange/search-unifiedauditlog?view=exchange-ps#-highcompleteness

It says:

> The HighCompleteness switch specifies completeness instead performance in the results. You don't need to specify a value with this switch.
>
>When you use this switch, the query returns more complete search results but might take significantly longer to run. If you don't use this switch, the query runs faster but might have missing search results.

Did you know about this parameter? Did you actually experience any incomplete logs when comparing output with and without it? Would it make sense to include it in the cmdlet calls in this project?

**Comment by invictus-korstiaan** [comment]
Hi Passimist, thanks for bringing this to our attention. We were not aware of this parameter, we look through GitHub and found it was only recently added in the last two weeks. We will most likely add this to our script as we want to make sure we acquire everything.

**Comment by JoeyInvictus** [comment]
Hi @Passimist, 

Small update. We've been conducting some tests, but the flag appears to be very unstable, resulting in errors most of the time. We attempted to integrate it into the Extractor for testing. Additionally, simply running the Search-UnifiedAuditLog cmdlet with this parameter results in errors over 50% of the time. There seems to be little information available online about this new parameter, and I was wondering if you had already conducted any testing?

![image](https://github.com/invictus-ir/Microsoft-Extractor-Suite/assets/129975292/601e4c68-ed99-4449-91d9-5df1a0a0b39c)

**Comment by Passimist** [comment]
Hey @JoeyInvictus,

I sadly do not have more experience with this than you. I was thinking about contacting Microsoft support to get more information since the documentation is rather disappointing. But as you probably know it is uncertain if this will lead to anything. 😆 
But since I was trying out your Microsoft Extractor Suite the same day that I stumbled over the "highcompleteness" parameter I figured I might as well ask here if you took this parameter into account.

Honestly I am hoping that this parameter will disappear again. Its description suggesting that log acquisition is incomplete by default is super concerning...

But maybe I interpret the parameter description wrong and it is actually used to acquire more logs than the limits that exist for some sources usually allow, which would be pretty cool.

**Comment by JoeyInvictus** [comment]
Hi @Calvindd2f, 

Thank you for your response! What do you mean by "the results are still processing"? I agree with using the try-catch if we add this to the tool. However, I'd like to do some more testing because the cmdlet for me seems pretty unstable at the moment and takes significantly longer than running it without the flag. I would also like to see the difference in records that are acquired with and without the flag.

**Comment by JoeyInvictus** [comment]
Hi @Calvindd2f,

Thanks for the detailed explanation and the tests you performed. I believe that from a forensic perspective, the most important aspect is to obtain all the data, even if it means waiting longer. However, currently, the parameter feels quite unstable as it keeps throwing errors in our test environment. I can't imagine how it would be if dealing with a significantly larger dataset.

As shown in the screenshot below, I attempted to execute the command you provided, but it failed on all three occasions when I requested 180 days of history. Since this is a test tenant with limited events, it's concerning that the command failed even in this scenario. We've encountered tenants with event volumes exceeding 5000 per minute. If the command is already failing on our small environment, it raises significant concerns about its scalability and reliability.

![errors](https://github.com/invictus-ir/Microsoft-Extractor-Suite/assets/129975292/ccadbd07-0774-41f6-b9fd-7f729f6a12aa)

**Comment by JoeyInvictus** [comment]
Hi, I will close this issue for now. We will still track changes to the highCompleteness parameter and implement it when it's more stable. However, we just published a way to extract the unified audit log via the Graph API. We did some testing, and the Graph API is way more stable in returning the same amount of data compared to the search-unifiedauditlog cmdlet. Since Microsoft is moving more and more towards doing everything with Graph, we expect that this method will work better and way less time consuming.
