### ISSUE TITLE
Get ActivityLogs Error

### ISSUE THREAD

**Issue by etaylor77** [invictus-ir/Microsoft-Extractor-Suite#43]
Sorry it took so long to get back with you. The previous issue was closed so was unable to respond to it. 

With the recent update, it mixed most of the issues I was having. However, this one is still haunting me. I even tried to run this in verbose mode to see where it might be getting hung up, but there is no output. 

`PS C:\Tools\Microsoft Extractor Suite> Get-ActivityLogs -Verbose
[WARNING] You must call Connect-AzureAZ before running this script

PS C:\Tools\Microsoft Extractor Suite> Connect-AzureAZ

PS C:\Tools\Microsoft Extractor Suite> Get-ActivityLogs -Verbose
[WARNING] You must call Connect-AzureAZ before running this script`

It is like the session token is not getting passed properly. I have the new Graph.beta module installed as well.

**Comment by JoeyInvictus** [comment]
Hi!

Before execution, the script verifies its capability to run the intended PowerShell cmdlet. If it fails, it will shown an error message: "You must call Connect-AzureAZ before running this script". While not being connected is a common scenario, it's important to note that other underlying issues may also prevent the cmdlet from executing, thereby triggering this warning.

```
try {
    $areYouConnected = Get-AzActivityLog -ErrorAction stop -WarningAction silentlyContinue
}
    catch {
        write-logFile -Message "[WARNING] You must call Connect-AzureAZ before running this script" -Color "Red"
	break
}
```

Could you attempt to execute the PowerShell cmdlet `Get-AzActivityLog`? This will reveal the actual error, since the error will not be catched by our script.

This function requires the following module to be installed:
`Install-module -name Az`

**Comment by JoeyInvictus** [comment]
Hi @etaylor77 , did you manage to get it working?
