### ISSUE TITLE
Get-Sessions - No output

### ISSUE THREAD

**Issue by rocket-ops** [invictus-ir/Microsoft-Extractor-Suite#44]
When trying to run 'Get-Sessions' the output is just an empty csv file. An example of the command ran was:

Get-Sessions -StartDate 11/19/2023 -EndDate 2/12/2024 -UserIds test@test.com

It appeared to run, but returned an empty csv. Attempted with no dates, and also changing the default output and nothing returned either.

**Comment by Fierry137** [comment]
Can confirm, also observed this behaviour yesterday. Similar behaviour was noted by the Get-MessageIDs command

**Comment by JoeyInvictus** [comment]
Hi @Fierry137 @rocket-ops,

Could you please run the following command to check if there are any results? Additionally, what type of license do you have? 'MailItemsAccessed' used to be included in the E5 licenses, but since Microsoft is now making new (premium) logging available for Audit (Standard) environments, this might not be the issue here.

`Search-UnifiedAuditLog -StartDate "2023-11-19" -EndDate "2024-02-12" -Operations "MailItemsAccessed" `

**Comment by rocket-ops** [comment]
Thanks. Totally missed that requirement. The command worked.

**Comment by JoeyInvictus** [comment]
@rocket-ops no problem! Microsoft is working on making the advanced audit logging available for everyone, so should be able to use the MailItemsAccessed operation soon for free :)
