### ISSUE TITLE
Mail.ReadBasic.All Permission for Get-Mail Error "scope does not exist"

### ISSUE THREAD

**Issue by drunkwithpower** [invictus-ir/Microsoft-Extractor-Suite#85]
Sorry of this is the wrong place to ask this question.

When I try to use the "Get-Email" command to pull an email associated with a specific message ID, the requirement is to connect with the appropriate permission so Graph will allow access to the email. When I attempt to connect via the command 'Connect-MgGraph -Scopes ‘Mail.ReadBasic.All’ I get the following error:

Error: The application 'Microsoft Graph Command Line Tools' asked for scope 'Mail.ReadBasic.All' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'

Is there a series of steps I can take to make sure the required permission is allowed and I can download emails? Am i the only one receiving this error or is this common?

**Comment by JoeyInvictus** [comment]
Hi, feel free to ask any questions here. :)

Unfortunately, the scope `Mail.ReadBasic.All` is an application permission. It's not possible to use it with delegated permissions, meaning a user account that you use to connect with `Connect-MgGraph`. The only way to get this to work is by assigning the permission to an application and using that application to connect to MgGraph.

**Comment by JoeyInvictus** [comment]
Unfortunately, not that I am aware of. You can use Content Search to find and download the messages, but this  isn't automated. 

Nowadays, we're more and more asking clients to provide an application with the required Graph permissions for our investigation instead of using a user account. Now a days you can also access the Unified Audit Log through Graph. Although it's still a bit buggy on Microsoft's end, you can retrieve information such as sign-ins, audits, risky users/detections, UAL, emails, user, and MFA details through an app registered in the client's environment.

If you want to do something cool, you can even create a 'multi-tenant' application in your own environment and deploy it via a simple consent flow in your clients' environments to collect logging through your own application. We did build all sort of automated workflows in collecting, processing and analyzing data from Azure/M365.

Another issue we're facing with the `Mail.ReadWrite` permissions is that clients find it concerning, as it grants the ability to delete all emails and more. It would be great if Microsoft could provide a simple Read permission that only allows reading emails without the ability to modify or delete them. The Mail.ReadWrite permission `allows the app to create, read, update, and delete emails in user mailboxes, but it doesn't include permission to send mail.`

With delegated permissions, so NO application needed, you can use the `Mail.ReadBasic.All` scope to retrieve basic email header information. However, this scope won't allow you to access the full email content.

The Mail.ReadBasic.All permission allows the app to `read basic mail properties in all mailboxes without requiring a signed-in user. This includes all properties except the email body, previewBody, attachments, and any extended properties`.

Hope this helps!

**Comment by drunkwithpower** [comment]
It does! 

:Nowadays, we're more and more asking clients to provide an application with the required Graph permissions for our investigation instead of using a user account." - This would seem to be the only avenue to automatically pull the email based on message IDs. I guess I will have to hone my development skills as this is beyond my expertise. Consulting for BECs just got a lot more complicated for everyone.

**Comment by JoeyInvictus** [comment]
I'm not sure if you have any experience with creating an app in Azure, but it's actually pretty easy. You can set up an app with the necessary permissions in under a minute without any coding using the Azure portal's GUI, no development skills required for this part!

https://learn.microsoft.com/en-us/azure/healthcare-apis/register-application

I'll go ahead and close this issue for now. If you have any more questions or need further assistance, feel free to respond here or open a new issue.
