### ISSUE TITLE
The term 'Get-AzureADAuditDirectoryLogs' is not recognized

### ISSUE THREAD

**Issue by rorywag** [invictus-ir/Microsoft-Extractor-Suite#89]
When attempting to collect "Get-ADAuditLogs" the following error message is produced.

`[ERROR] An error occurred: The term 'Get-AzureADAuditDirectoryLogs' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

Hopefully just a layer 8 issue (moi) but looking to be something else.

**Comment by JoeyInvictus** [comment]
Hi, have you installed the `AzureADPreview` module and connected using `Connect-AzureAD`? It seems like the underlying module required by the Microsoft Extractor is missing. This often happens when the module hasn't been installed or the connection hasn't been established.

Make sure to import the correct module:
`Import-Module -Name AzureADPreview -Force
`

Could you try running the following command:
` Get-Command -Module AzureADPreview | Where-Object { $_.Name -eq 'Get-AzureADAuditDirectoryLogs' }`

Do you see the necessary cmdlet in the output?

![image](https://github.com/user-attachments/assets/5ce187a1-e1b9-480b-9efa-049804c55028)

**Comment by rorywag** [comment]
Thanks Joey
